services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "false"
      N8N_WEBHOOK_URL: "https://47f85f182cfc.ngrok-free.app"
      N8N_HOST: "47f85f182cfc.ngrok-free.app"
      N8N_PROTOCOL: "https"
      N8N_PORT: "5678"
      N8N_TUNNEL_URL: "https://47f85f182cfc.ngrok-free.app"
      GENERIC_TIMEZONE: "America/New_York"
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always
